### ISSUE TITLE
Please add inventory verification

### ISSUE THREAD

**Issue by LimiQS** [SapphireServer/Sapphire#181]
I mistyped `//gm item 20956` to `//gm item 30956`. And a "naught" (just like nothing is there) is added to my inventory and occupied one of my inventory slot. When I want to remove it, I found it's impossible because it's "naught". So I decided to remove the DB record via SQL. I typed in the SQL, run it, no error, no warning. But nothing happened. Then, when I rearrange my items, the "naught" is recorded again in the DB. It seems like no inventory item verification is implemented on the server. Server will record client's message as-is.

Repro:
1. `//gm item 30000`
2. Delete data (set to `0`) related to it in `charaiteminventory`
3. Move anything (item X) from one slot (slot A) to the slot belong to `item 30000` (slot B)
4. Check the `charaiteminventory` table. What should be removed now appeared again. DB recorded that `item 30000` at slot A, and item X at slot B

**Comment by GokuWeedLord** [comment]
did you edit the db while you were logged in?

**Comment by SapphireMordred** [comment]
Yea, we should doublecheck the Item for validity. Though care needs to be takes as there are items in the exds that would show up without icons, so those, too need to be filtered

**Comment by LimiQS** [comment]
@GokuWeedLord Yup. I knew it's unsafe but still did that. 🚫 But, in a similar way, one with a packet capture tool can easily copy or add items since there is no verification on input data. It's disastrous.

**Comment by itsMaru** [comment]
I was not able to reproduce adding an item that the exd reader isn't able to pull info out of, but was able to add an item that is completely blank.

#169 adds an extra check for whether an item is blank or not (which may be changed on what property it checks).

> But, in a similar way, one with a packet capture tool can easily copy or add items since there is no verification on input data. It's disastrous.

Not quite sure I follow - you'd need to build and send a packet from client to execute //gm item, which is then handled by the GMCommandHandler.. which verifies whether the user is a GM and if they're of sufficient rank. Mind providing an example on how a crafted packet could abuse this item handler?

**Comment by GokuWeedLord** [comment]
Pretty sure they're saying that an item can be moved without it being removed from the previous slot, but I'm not quite sure how that would work 

https://github.com/SapphireMordred/Sapphire/blob/master/src/servers/Server_Zone/Inventory/Inventory.cpp#L504-L515

**Comment by NotAdam** [comment]
The issue described here isn't actually an issue, removing an item from the db while a player is logged in will not remove the item from the player as inventories are stored in server memory which the server will then insert into the db when you move the item.

To remove an item from a player at the moment, player needs to be logged out and then the item removed from `charainventoryitem` and then its id removed from the players `charaiteminventory` row depending on where the player had the item.

mordred pls close
