### ISSUE TITLE
Build system refactoring

### ISSUE THREAD

**Issue by ayyaruq** [SapphireServer/Sapphire#182]
The current CMake build system is kinda complicated, prone to errors (Boost in VS 2017 on Windows, zlib on Mac/Linux, the recent MySQL path issue...) plus the external dependencies and libs are a bit painful. I'm making this issue to address the known issues plus whatever we find along the way to simplify the build system.

The major proposal is to update CMake minimum version to 3.1, although CI uses 3.5 as a minimum anyway (Ubuntu Trusty), and use the pre-packaged CMake modules for things like Boost, Doxygen, GTest, zlib, or whatever else we currently use or want to use. Additionally, the way external projects are pulled in and built is kinda complex and requires manual work which CMake should be able to manage, for example updating submodules. I'm not sure how that works for tarball builds though.

- [x] CMake minimum version 3.1
- [ ] Use CMake's packaged FindBoost
- [ ] Add missing explicit dependencies (pthread and zlib - dl is a macro)
- [ ] Add CMake packaged FindZlib
- [ ] Add CMake packaged FindThread
- [ ] Use ExternalProject for SapphireLibs
- [x] Investigate separating SapphireLibs external and internal dependencies
- [x] Add VS2017 generators to CMakeSettings.json
- [ ] Add CI for VS2017 targets
- [x] Rename targets ( Server_Zone -> sapphire_zone, etc.... )

**Comment by SapphireMordred** [comment]
Closing since the buildsystem changed due do general reworking and move to c++17
