### ISSUE TITLE
Out-of-date Quest Parse Templates

### ISSUE THREAD

**Issue by goaaats** [SapphireServer/Sapphire#388]
Due to scripting API changes, the template used for script generation is out of date:

- Changed callback structure( now ``[ & ]( Entity::Player& player, const Event::SceneResult& result )``)
- Use of Player::playScene and playSceneChain instead of eventPlay
- Bad syntax in generated arrays for quest rewards

**Comment by takhlaq** [comment]
think this can be closed now
