### ISSUE TITLE
FFXIVIpcLobbyError - Structure change in 4.4

### ISSUE THREAD

**Issue by AetherShane** [SapphireServer/Sapphire#400]
Hi, just leaving a note. FFXIVIpcLobbyError added 4 bytes after error_id and before param. I've went through quite a few lobby errors and have been unable to get anything other than 0.

-- Edit --
Forgot to mention, leftover/message[] seems to be 514 now, not 516.

**Comment by takhlaq** [comment]
can probably close this since we no longer support 4.4
