### ISSUE TITLE
Mobs don't despawn properly

### ISSUE THREAD

**Issue by goaaats** [SapphireServer/Sapphire#48]
Killed mobs don't despawn properly in certain cases, and reappear with a depleted health bar after a player goes back in range of them. This seems to happen with mobs spawned manually and with our current db solution.

![image](https://user-images.githubusercontent.com/16760685/29250454-efa70152-8042-11e7-9afb-a74d3f344aec.png)

**Comment by SapphireMordred** [comment]
Closed since mobs are being reimplemented

**Comment by SapphireMordred** [comment]
We have a similar issue now with the new implementation.
Mobs being despawned sometimes respawn instantly while still being dead.
My guess is that they are not being removed from the world properly.

**Comment by SapphireMordred** [comment]
Some initial tests suggest that the bnpc was no longer in the cell list. Take this with a grain of salt though.
It has to still be somewhere as even re-logging does not make it disappear
