### ISSUE TITLE
IPC code I found

### ISSUE THREAD

**Issue by LimiQS** [SapphireServer/Sapphire#565]
[C] 0x0075 = Cancel logout request (When in combat zone, there is a 20 sec countdown before a player can actually logging out. This OpCode indicates player pressed 'Cancel' button in this 20 sec grace period)
    Int64 SameValueAsTheOneIn0x0074

[S] 0x0194 = Retainer selling list item price information. (It will update price information in a retainer's selling list. Combining with ItemInfo message with same Seq, Cid and Slot, you could get the whole picture on what one is selling. One item per message, sent just after ContainerInfo message with same containerId.)
    Int32 containerSequence
    Int16 containerId
    Int16 unknown
    Int16 slot
    Int16 unknown
    Int32 unknown
    Int32 price
    ...unknown

**Comment by highlyunavailable** [comment]
There's 0x019F (was 0x194 in 4.5) which is not the same code as added in 8c2f585 - 0x019F loads the prices when you open a retainer (this issue) while 0x019D is the one that is sent from the client when you exit a retainer after updating a price. Both are valuable but they mean different things.

**Comment by NotAdam** [comment]
ah, must have got that one wrong then when I was trying to find the handler in the 5.0 exe - didn't check retail when I updated them.

Feel free to make a PR to change that opcode @highlyunavailable otherwise I'll fix it up later
