### ISSUE TITLE
Database issues

### ISSUE THREAD

**Issue by djkain34** [SapphireServer/Sapphire#575]
Cant get the database to import.  The following lines give errors in sql
`executionTime` datetime DEFAULT CURRENT_TIMESTAMP,
Error occured at:2019-08-11 03:35:35
Line no.:401
Error Code: 1067 - Invalid default value for 'executionTime'

`UPDATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
Error occured at:2019-08-11 03:35:35
Line no.:395
Error Code: 1067 - Invalid default value for 'UPDATE_DATE'

Using 5.5.62 of mysql

**Comment by SapphireMordred** [comment]
5.5 is pretty old, i'd suggest using 5.7 which is also what we use for development.
