### ISSUE TITLE
Mob just standing 

### ISSUE THREAD

**Issue by aevers34** [SapphireServer/Sapphire#576]
When killing lower level mods they just stand there and don't fight back.  Also they don't walk around or move after the mob dies no exp is given.  Any idea's what might be causing this.  Upgrading to 5.7 SQL fixed the DB issue I was having thanks for that BTW

**Comment by Regiuz** [comment]
Did you generate the navigation meshes? Without those mobs wont be able to do much.

**Comment by aevers34** [comment]
I did create the Navigation meshes it went thru with no errors as far as I know.  They show up and you can kill them just no exp or movement.

**Comment by aevers34** [comment]
Do you have to have up to Shadowbringer for this to work?

**Comment by NotAdam** [comment]
The only reason bnpcs won't do anything is if it can't get the navigation manger for the current territory

Can you post your logs?

**Comment by djkain34** [comment]
I might have figured out the issue.  looks like nav_export.exe keeps crashing before it finishes on the final part.  My guess its supposed to copy the files from pcb_exports to navi folder and it never finished.  Checking windows logs looks like a virtual memory issue.  I manually copied the files over and seems everything is now working.

**Comment by NotAdam** [comment]
It doesn't copy anything at all, it just writes everything to pcb_export, you need to move/copy the folder out of the tools directory and rename it

**Comment by aevers34** [comment]
It is working now it took about 4 trys to full run the program without crashing.  Thanks for the help.
