### ISSUE TITLE
Lobby and World appears issues

### ISSUE THREAD

**Issue by whatthetruth** [SapphireServer/Sapphire#606]
Some issues appears when i login the character.
①The client will stuck in Now Loading for long time.
②Lobby.exe will appear “GameConnection closed: End of file”
③World.exe will appear “[warn] No navmesh found for TerritoryType#XXX”.
There are about 20 ~ 30 such tips.
I checked that the maps pointed to by these tips are not exported in the pcb_export folder.

My client version is 5.11.
You can check this in this img link:https://img-hut.com/images/2019/12/09/543453064261279a84d1cad478e8a9d7.png

**Comment by whatthetruth** [comment]
https://img-hut.com/images/2019/12/10/ba3b14c1745af2e5f4b140c372d20610.png

**Comment by NotAdam** [comment]
1. Opcodes haven't been updated for 5.11 (or the hotfix) to the point where characters are able to login
2. Not a bug or a problem, working as intended
3. You didn't copy the folder with navmeshes inside the tools director to the navi folder next to the world executable

**Comment by whatthetruth** [comment]
> 1. Opcodes haven't been updated for 5.11 (or the hotfix) to the point where characters are able to login
> 2. Not a bug or a problem, working as intended
> 3. You didn't copy the folder with navmeshes inside the tools director to the navi folder next to the world executable

Thanks your answer.Can u show me the screen capture about the directory please？

**Comment by whatthetruth** [comment]
> 1. Opcodes haven't been updated for 5.11 (or the hotfix) to the point where characters are able to login

Thanks your answer,the issue of ③ has been fixed.
Im waiting your update. :)

**Comment by takhlaq** [comment]
old, can be closed
