### ISSUE TITLE
World server crashes after character creation

### ISSUE THREAD

**Issue by djkain34** [SapphireServer/Sapphire#636]
I can now login but after the character creation the world server crashes.  Tried 2 different client versions 2019.07.24.0001.0000 and a newer version that i have at work.
![world crash](https://user-images.githubusercontent.com/52115587/74702753-96024500-51d0-11ea-91e8-bc0423efbdb1.jpg)

**Comment by NotAdam** [comment]
2019.07.24.0001.0000 is extremely old and won't work at all unless you pick an older version of the server, it's not backwards compatible at all

**Comment by NotAdam** [comment]
also the screenshot is pretty useless, build with `RelWithDebInfo` or `Debug` otherwise you won't get anything usable

**Comment by djkain34** [comment]
what version is best? just wish you could update it without having a current account.

**Comment by djkain34** [comment]
CMake command arguments: have -DCMAKE_BUILD_TYPE="RelWithDebInfo"

**Comment by NotAdam** [comment]
only newest client version is supported, anything outside of that means you're on your own.

It looks like exd reading that's failing there though, but for whatever reason it's not loading symbols, either because they don't exist or it was built on another computer and copied to the vm, so VS will fail to load them by default

**Comment by djkain34** [comment]
It was compiled on this vm.  I just ran it from the cmake folder and it crashed the same way.  How do I check if its loading the symbols?

**Comment by NotAdam** [comment]
If it was built on the same machine it should just load them anyway

there are *.pdb files in the bin directory?

**Comment by djkain34** [comment]
Nope only see .exe files .sh and .dll

**Comment by djkain34** [comment]
I think I figured out how to get them and now have a new shot.
![world crash2](https://user-images.githubusercontent.com/52115587/74798797-67e63900-5294-11ea-9d51-233442a6896f.jpg)

**Comment by djkain34** [comment]
I did notice the new character doesn't have cloths on.
![new char](https://user-images.githubusercontent.com/52115587/74799814-49ce0800-5297-11ea-8ed0-bc8d831a2af6.jpg)

**Comment by NotAdam** [comment]
yeah, that problem is because your game version doesn't match the server so it won't be able to read sheets in the event that the columns move around

clothing issue because you crashed during login and the opening didn't play through correctly

**Comment by djkain34** [comment]
fun guess its time to buy a game card to get the game up to date.

**Comment by NotAdam** [comment]
you can use the trial to update your game too, but naturally you won't have any expansion content by default.

**Comment by djkain34** [comment]
I re-activated my account and downloaded the full thing.

**Comment by ffxisf** [comment]
need check version load packet parse model

**Comment by djkain34** [comment]
ffxisf is that something I can do?  I can't program but can try and help yall out any other way if yall need it.

**Comment by djkain34** [comment]
Looks like this new update made it work.  Thanks a ton
