### ISSUE TITLE
ChatHandler opcode is wrong for me

### ISSUE THREAD

**Issue by folkvir** [SapphireServer/Sapphire#664]
Hey !
I discovered that the opcode for the ChatHandler might be wrong in my case.
It seems to be my Blacklist. 

From the develop branch:
https://github.com/SapphireServer/Sapphire/blob/338504a9ea013a1bea7fb7dd94bf71604912830d/src/common/Network/PacketDef/Ipcs.h#L305

Then I found that the structure could be this one (010 Editor template)
```c++
LittleEndian();
struct ChatHandler {
    struct Header {
        uint length;
        uint actor_id;
        uint login_id;
        ushort segment_type;
        ushort unknown1;
        ushort reserved;
        ushort type;
        ushort unknown2;
        ushort server_id;
        uint timestamp;
        uint unknown3;
    } header;
    byte padding[8];
    struct Entry {
        uint actor_id; // not sure about this but it seems to be an actor_id
        ushort unknwown1;
        ushort unknwown2;
        ushort WorldID;
        ushort WorldID1;
        ushort status;
        char name[32];
        byte padding[2];
    } entries[10];
} chathandler;
```

The total length of my message is 520 bytes, so 488 bytes without the header

1) The header is the common message header of length 32 bytes.
2) Then perhaps some padding of 8 bytes length.
3) An array of 10 entries with:
3.1) perhaps the actor_id
3.2) 2 unknowns things for now but in my case it is often (`46` and `64`) or (`23`and `64`)
3.3) 2 worlds id, I verified this with the list of World IDs from ffxiv-datamining and it seams ok.
3.4) a Flag perhaps, for now it is 0, 1, or 2
3.5) the name of length 32 bytes
3.6) something unknown always at 0

As an example I decoded the message with my own parser: 

````js
FFXIVMessageChatHandler {
  Header: FFXIVMessageHeader {
    MessageLength: 520,
    ActorID: 275729684,
    LoginUserID: 275729684,
    SegmentType: 3,
    SegmentTypeString: 'IPC',
    Unknown1: 0,
    HeaderLength: 32,
    Reserved: 20,
    MessageType: 393,
    Unknown2: 0,
    ServerID: 0,
    Timestamp: 0,
    Unknown3: 0
  },
  Unknown: <Buffer 00 00 00 00 00 00 00 00>,
  Blacklist: [
    {
      ActorID: 2464589616,
      Unknown1: 46,
      Unknown2: 64,
      WorldID: 83,
      WorldID1: 83,
      Flag: 0,
      Name: '******** *****',
      Pad2: 0
    },
    {
      ActorID: 2462647377,
      Unknown1: 46,
      Unknown2: 64,
      WorldID: 71,
      WorldID1: 71,
      Flag: 0,
      Name: '******** *********',
      Pad2: 0
    },
    {
      ActorID: 2466931369,
      Unknown1: 46,
      Unknown2: 64,
      WorldID: 83,
      WorldID1: 83,
      Flag: 1,
      Name: '******** ********',
      Pad2: 0
    },
    {
      ActorID: 2464401528,
      Unknown1: 46,
      Unknown2: 64,
      WorldID: 0,
      WorldID1: 0,
      Flag: 2,
      Name: '',
      Pad2: 0
    },
    {
      ActorID: 1248595809,
      Unknown1: 23,
      Unknown2: 64,
      WorldID: 83,
      WorldID1: 83,
      Flag: 1,
      Name: '**** *******',
      Pad2: 0
    },
    {
      ActorID: 0,
      Unknown1: 0,
      Unknown2: 0,
      WorldID: 0,
      WorldID1: 0,
      Flag: 0,
      Name: '',
      Pad2: 0
    },
    {
      ActorID: 0,
      Unknown1: 0,
      Unknown2: 0,
      WorldID: 0,
      WorldID1: 0,
      Flag: 0,
      Name: '',
      Pad2: 0
    },
    {
      ActorID: 0,
      Unknown1: 0,
      Unknown2: 0,
      WorldID: 0,
      WorldID1: 0,
      Flag: 0,
      Name: '',
      Pad2: 0
    },
    {
      ActorID: 0,
      Unknown1: 0,
      Unknown2: 0,
      WorldID: 0,
      WorldID1: 0,
      Flag: 0,
      Name: '',
      Pad2: 0
    },
    {
      ActorID: 0,
      Unknown1: 0,
      Unknown2: 0,
      WorldID: 0,
      WorldID1: 0,
      Flag: 0,
      Name: '',
      Pad2: 0
    }
  ]
}
```

**Comment by collett8192** [comment]
I'm not sure what you are getting here. ChatHandler is an outgoing packet from client that means if the opcode is wrong it's impossible to collide with Blacklist which is an incoming one.
As far as I can tell, this handler is working correctly in Sapphire.

**Comment by folkvir** [comment]
Ok sorry for the lack of context. 
I assume that "// updated 5.25" is related to the current patch version. Assuming that the Sapphire server version is related to the game patch, then, the opcode for ChatHandler is wrong. 
I recorded my self network packets using my own sniffer and parsed them just like Machina.FFXIV does. And it appears that, for an incoming or outcoming packet, I have an opcode corresponding to "0x0189"  which is for me a blacklist message and not a ChatHandler message.
That's why I'm posting an issue here. Perhaps it is not the right place to report this kind of thing?

**Comment by collett8192** [comment]
It is for current patch, and 0x0189 is correct ChatHandler opcode, Blacklist is 0x027A.
I recheck them a minute ago to make sure I'm not talking out of thin air.

**Comment by folkvir** [comment]
That's really weird... I didn't invent this opcode. As you can see in my decoded message the `Header. MessageType` is 393 which `0x0189`. If it is an error in my parser I shouldnt be able to decode other stuff correctly ><

**Comment by folkvir** [comment]
Ok, news about this.
I used the current FFXIVMon to record some chat logs in order to reproduce this.
During this session I tested:
* /tell => opcode 0x0064 for server and client
* /shout /say /yell => opcode for the server is 0x0161 and client is 0x0189
* /fc /p with opcode 0x0065 for server and client

And I didnt found trace of my message sadly.
But I continued a bit and finally logout and login back with my current character. After some times the server has finnally sent a message with opcode 0x0189 which represents my black list.
I'm definitely not crazy!

![image](https://user-images.githubusercontent.com/7128943/81019585-43e3ce00-8e67-11ea-925e-3b1d644372cb.png)

Maybe there is something wrong with the parser or maybe there is a flag which turn the message into a blacklist ><
Or maybe this message is a safety for not receiving messages from blacklisted characters.

**Comment by collett8192** [comment]
Then it does not matter whatever this packet is, ChatHandler is still correct since server and client packets can share the same opcode for completely unrelated packets. When login, checkout opcode 0x027A (server to client, orange), that one is blacklist. I'm not sure what is this and I have one in one of my captures containing a single character I don't know about.

**Comment by folkvir** [comment]
Yeah for sure ChatHandler is still correct. If this is just routing of packets internally, we should have a flag in the message to sort this out. Anyway this is another story. At least we have the trace of this in the issue. Thank you for the help. I'll close this.

**Comment by NotAdam** [comment]
cross-instance chat (fc, tells, linkshells, etc) are done on a separate connection to world and you can distinguish them that way, otherwise check the packet header and use the relevant field:

https://github.com/SapphireServer/Sapphire/blob/develop/src/common/Network/CommonNetwork.h#L60-L61

also it looks like the first 8 bytes of that packet is actually the content id and not the actor id, no idea what it would be for though

    2464589616 << 32 | 46 << 16 | 64 = 18014598542567216 = 0x0040002E92E6A730

same id range as content ids usually are
