### ISSUE TITLE
world.exe problem with DataPath in global.ini

### ISSUE THREAD

**Issue by mangamaniacs2064** [SapphireServer/Sapphire#688]
here is the game i installed the trial version last version on the officalwebsite..

the game is installed on  D:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
here is the global.ini datapath:

DataPath = D:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\sqpack

when i start the world.exe after loggin.exe... it says:

 [fatal] Error setting up generated EXD data. Make sure that DataPath is set correctly in global.ini
[20:40:00.558] [fatal] DataPath: D:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\sqpack

**Comment by NotAdam** [comment]
are you on master or develop? you should be on develop

**Comment by mangamaniacs2064** [comment]
I dont know where can i see that?

**Comment by DantestyleXD** [comment]
According to Wiki:
Did you set DataPath like this `C:\\Program Files (x86)\\SquareEnix\\FINAL FANTASY XIV - A Realm Reborn\\game\\sqpack` with double Backslashes?

**Comment by mangamaniacs2064** [comment]
no normal \ not 2 times.. why? is it \\?

**Comment by DantestyleXD** [comment]
Replace your `D:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\sqpack` with this 
`D://Games//SquareEnix//FINAL FANTASY XIV - A Realm Reborn//game//sqpack` and try again

**Comment by mangamaniacs2064** [comment]
no even with 1/ or 2/ nope...
do i have to install mysql or another software? i just downloaded the compiled version of saphire

**Comment by DantestyleXD** [comment]
Sorry, was `D:\\Games\\SquareEnix\\FINAL FANTASY XIV - A Realm Reborn\\game\\sqpack`...

**Comment by mangamaniacs2064** [comment]
i installed the trial version on the official site.
and then: i tried // ­­\\ / and \
neither of them works...
i didnt installed mysql

**Comment by mangamaniacs2064** [comment]
Error setting up generated EXD data. Make sure that DataPath is set correctly in global.ini
[10:57:39.478] [fatal] DataPath: D:\\Games\\SquareEnix\\FINAL FANTASY XIV - A Realm Reborn\\game\\sqpack

**Comment by DantestyleXD** [comment]
You need to have mysql for sapphire database and set global.ini correctly with mysql infos but this is not the problem that you mention.

I think the problem is your compiled version: last compiled exes are made for 5.1, actual client patch is 5.25
So, in this case, it can't reach EXD data 'cause it can't "decrypt" them (IMHO)

<details>
  <summary>Spoiler </summary>
Probably someone like Adam can correct me if I wrong

</details>

**Comment by mangamaniacs2064** [comment]
ok.. i need to have a client lower  version like 5.1? if thats the case where to find that... it au update when ilaunch the launcher

**Comment by mangamaniacs2064** [comment]
Can i have the  client 5.1?


Envoyé de mon téléphone intelligent Xperia par Sony


---- DantestyleXD a écrit ----


You need to have mysql for sapphire database and set global.ini correctly with mysql infos but this is not the problem that you mention.

I think the problem is your compiled version: last compiled exes are made for 5.1, actual client patch is 5.25
So, in this case, it can't reach EXD data 'cause it can't "decrypt" them (IMHO)

Spoiler Probably someone like Adam can correct me if I wrong

**Comment by DantestyleXD** [comment]
We can't provide you a client but we can indicate how to compile Sapphire.
Follow this guide and you can use the latest client: [https://github.com/SapphireServer/Sapphire/wiki/Windows-Installation](url)

You can join Sapphire Discord Server too for better informations and know about the project!

**Comment by mangamaniacs2064** [comment]
thanks but No results matched your search.

**Comment by mangamaniacs2064** [comment]
okay wshen i copy paste the adress it work  but wheni  click,..;.. nothing.... thats fine then..

**Comment by NotAdam** [comment]
there's no 'decrypting', it just doesn't work if the version doesn't match.

`git checkout develop` is 5.25, checkout one of the tags for a previous version if you have an old client. this is covered on the wiki so I'd recommend you read that instead.
