### ISSUE TITLE
Any commands for instance map phase transition?

### ISSUE THREAD

**Issue by AiwassPrime** [SapphireServer/Sapphire#703]
I am new to this project. Anyone knows any command for instance map phase transition?
For example, I create an instance of ucob, and I want to view phase 2/3/4/5 map, is there a way to do that?
Thank you in advance.

**Comment by JeidoUran** [comment]
This is usually done by changing the weather. In UCoB's case, if I remember correctly it's done by using different versions of the "Fair Skies" one for the earlier phases, and the last phases are done using Final Coil Turn 4's ones.

**Comment by AiwassPrime** [comment]
> This is usually done by changing the weather. In UCoB's case, if I remember correctly it's done by using different versions of the "Fair Skies" one for the earlier phases, and the last phases are done using Final Coil Turn 4's ones.

That works! Thank you very much.
