### ISSUE TITLE
Adding new IPC code definition?

### ISSUE THREAD

**Issue by p-doyle** [SapphireServer/Sapphire#704]
I've been messing around with housing stuff and identified one of the currently unknown opcodes, 0x0096, and was wondering if its possible to have this added to the packet definitions?  The opcode is 0x0096 and contains information on the house listings when you are viewing the residential district wards.  I am guessing you will need more information than that but not sure what all is required.

**Comment by NotAdam** [comment]
the most useful thing really is the structure itself, opcodes don't mean much any more given they change every time they patch the client exe

**Comment by p-doyle** [comment]
Of course.  I was just hoping to get some more information on the best way to move forward.  My ultimate goal is to have this available downstream in the node-machina-ffxiv project and I made a struct for use with that project but not sure what all is required for the structs in Sapphire for ServerZoneDef.h.  I could probably cobble something together but am not as familiar with this project and wouldn't have an easy way to test it.

**Comment by NotAdam** [comment]
ah, basically all it _needs_ is the structure itself, but it's more useful if you add something to ipcs.h which also contains the opcode and the version it was last updated.

in terms of the structure itself, it doesn't need anything special and as long as it builds there's really no issue. no requirement for you to actually implement anything for the packet in question, some documentation is better than none at all
