### ISSUE TITLE
Fail to build Sapphire

### ISSUE THREAD

**Issue by AiwassPrime** [SapphireServer/Sapphire#712]
**Describe the problem:** I followed the wiki and tried to build the server. I did not change any of the codes. Please help!

**Screenshots or videos needed to identify the problem:** 
![image](https://user-images.githubusercontent.com/58588910/111033329-b4765680-844b-11eb-96a2-088026ec7ee2.png)

**Comment by NotAdam** [comment]
delete the japanese text or fix the file encoding in VS
