### ISSUE TITLE
Failed to build Sapphire

### ISSUE THREAD

**Issue by QueXArt** [SapphireServer/Sapphire#818]
![Screenshot 2022-08-20 111053](https://user-images.githubusercontent.com/106489625/185760818-776c7b76-2e57-4298-97c9-1ac7e8dbb5e1.png)
Tried every setting I can think of, build ends right there every time.

**Comment by ZroIsHere** [comment]
Lo stai compilando in x64/release?

**Comment by QueXArt** [comment]
I was, but I figured it out, I was missing Cmake, so, it compiled after I installed and added to path.
