### ISSUE TITLE
In Branch Sapphire_Retail, the oo2net_9_win64.lib file is missing in the deps/Oodle directory

### ISSUE THREAD

**Issue by chang196700** [SapphireServer/Sapphire#951]
In Branch `Sapphire_Retail`, the `oo2net_9_win64.lib` file is missing in the `deps/Oodle` directory, `deps/Oodle/CMakeLists.txt` requires it.

**Comment by NotAdam** [comment]
working as intended, you need to source that yourself as we can't distribute it.
